version "2.4"

//Base actors
#include "zscript/weasle/base/base_actor.zsc"
#include "zscript/weasle/base/base_fx.zsc"
#include "zscript/weasle/base/base_projectiles.zsc"
#include "zscript/weasle/base/base_weapon.zsc"

//Ammo
#include "zscript/weasle/pickups/ammo/plasma.zsc"

//Armor

//Health

//Powerups

//Weapons
#include "zscript/weasle/weapons/plasmarifle.zsc"
#include "zscript/weasle/weapons/lunsolrifle.zsc"